[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.3",
    "python-telegram-bot>=20.7",
    "yt-dlp>=2025.2.19",
    "telegram>=0.0.1",
    "beautifulsoup4>=4.13.3",
]
